sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
- docker

language: python

python:
- "3.6"

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

  - pip install --upgrade pip
  - pip install -r requirements.txt
  - flake8 src test

  - cd bin
  - ./pull.sh

  - cd ../..
  - git clone https://github.com/jameshnsears/xqa-test-data
  - cd xqa-perf

script:
  - export PYTHONPATH=src:test:$PYTHONPATH
  - pytest -s --cov-report term-missing --cov . test/xqa

after_success:
  - COVERALLS_REPO_TOKEN=BjqwtkfNDYaiJng8qgld3mS8ROW23xc0c coveralls
