sudo: required

notifications:
email: james.hn.sears@gmail.com

env:
  global:
    # travis encrypt COVERALLS_REPO_TOKEN=...
    - secure: "u/ukkuWPOGb+J1tkKGDbpV2YlJiiUFJy5NC+BUju/c2DZUtmfWn4poALq3PJbvin9CtGL/W0HEsK1ysMhh6gw91S6cYEhHTCiW0cUZgqv5MJOqkd5YGQPbeT2t3RnTjEiwSHfbcsds0nUETwBOsYvT6FSqpcqt0f/FsRyYpmwr/jJnVA7RkkFylY10uSVrhoCbm9UToYgQIAgfFx21lLRWvHnP4zagEYyhqJobd1j1cL9raJA08wKkC5SUFL5Lb3ONTxFQuRTKAMnucRRjlMYl1fJDSjQ1OhUcYep51A6GOt0KmReW79l1ecLdfQL+gq6T+Lm0hBXMLzfaLNxCDw93PjnX8EqFpxRmZtx+BcFyTdiratWS8zSa7E9zXGDkpE2yN1ehkFItDhgnpjcx5iekl7H3fYXK9L9pU9EshwfsM/SaBOYecUTQTgka4kFpgaAOUADGjmnMd2y7lXES7+dhHOYA6llUEkKBdrlSmrhJ3uF8J0vzmmCbNFJEkSY/Y+k7y9S3pDbsb0xLyYApzGX7P84EZ9BmTaj6MzrnR+xwW0ikOdX8d96wZr5TGrRgrn8CFVUfUSuH0Ublvmb2Vwz2CihcccUhuk3Eh5+KXI5iW8o4grIVdB5HXawobpWuEDCMvmomc4EpDxi4mhVWEE/Gf/mwoYZnk9D0dkMFE1gz0="
    # travis encrypt CODACY_PROJECT_TOKEN=...
    - secure: "rymkA2GLY0o8I4K7vSRdYieNRWIo2Dksy2YbCm/vPhjoBjdiClpRsMtHTky55HFR/vy/Y/FtRRCJok38DvxBL/YMlOPnjz/RedG3wDVWa0JqhNJrgOP6HQ+Ig4RAAOSso3HCLZFl7V20dVSrV9+2KPt3Tl8Hz4kpE8BMpFmlZNYn1jOI8Y/SdHQR8VJ1U1q4GKDIs/ZtsJ4hgt5wExdnkW3xKElcPdqJTdpz6k9RnR+40ACy4x+wQ8oD5m4W+YxWhznZ3RVJaalAy6C212rHVQhzkb9ef/SN5dxrMfVjPkwtaNL9v76oiNsUm43TPOfWJJsHKS46308KHb5aO2Q/9WRGYbOZhlhzOwbOaixx5XFz3EZox/n9voBJ0IsfiAkO6/0a+Jv9gIIq7gFb/YbA2MuWVa+yKW1LZOGtBUDl2JuitBVKegqanmXPf8O9A2gnv7krXLA1fZHmhCP73qxoMmPV/jAflK8ZrPWYyk4CjEUJ49beAnmlvO1CYfrarPVVORHz3nV/+yTvhX1gD3Qxforr/9cxOfhG2qqcGxIAoVIOy5coggrKR4iXKjmgbzguMqvKk9tlqWIUN5xepBAhgJxAbZ/mKC8Ox8wc2ghD5vD+A9GINWuorsqqB73r8vOe8GuBWfBWvcVQ41HudNQw+aF8vyHFFt7ZjoGDjWPWSvo="

addons:
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "HqVVwA1c7ZCK3WMkBv03e0iYeHqsEBMmqn0xSp62PVSrRoEOJpWi5mT+hVa9hs9Ccz+VlaJpHrNsSGCD+p41GvwZg5ZPauCTgrctL3LGTVoCFSd8FQboTAQyWyBusTzDDJLqQsVwCxbU964o0QdIWWea5ZiNwI8cPVXyB/EQzXQzFoAo8rAbs2iq+xHiOOWY5XR9FGa9GcgbDnO1ufq7b+nX6NQ7W6Zcx7HlgMbvadeGa4VMC5+6Uilym4QG6bLdiyiAhlGtCzFrCZKXxG76pXSb973c9A631XIH/gUnF0RUj0l3//Th5Gu2+xRptK9PaTsBFR5oZ1aeFHWMgnEXLye4aGPdsqzJ8XNGiYay3sVtKHQ9DWVg7cQ0E8jPLZ9PdyhpsKS80ysFK5zGKh3UYUsbIWyyR5kTeF9PGscv7Y7k7qtPTeSfyeN4ig0yqGWQvUWuYO8n6nX4rJ2dV2gmQLjS7CFQHOvEd4GXPiS0ywwXPLZhULs0Bx0PTqS0i7C9i6UxacLo1nGBr8uhotCNij1lgTEEJ0eAHin4HRyPJZJT0aqPUR9T4K7EPGzGetbjAiJ9xtGSV+ZkC000TPKKtbwthr/NRbbuKhNUOwy/mKHZf1wVNA1br+T6TE0YywiWp7Tk7ohN+aA42CedBoYCzCkejGjDTp0O12h0Mma9J94="

git:
  depth: false

services:
  - docker

cache:
  directories:
  - $HOME/.sonar/cache

language: python

python:
  - "3.6"

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

  - pip install --upgrade pip
  - pip install -r requirements.txt
  - flake8 src test
  - export PYTHONPATH=src:test:$PYTHONPATH
  - pylint --rcfile=setup.cfg src test -r n > pylint-report.txt 2>&1 || true

  - cd bin
  - ./pull.sh

  - cd ../..
  - git clone https://github.com/jameshnsears/xqa-test-data
  - cd xqa-perf

script:
  - pytest -s --junitxml=junitxml.xml --cov-report term-missing --cov . test/xqa
  - coverage xml -i

after_success:
  - python-codacy-coverage -r coverage.xml
  - coveralls
  - sonar-scanner

after_failure:
  - docker images
  - docker ps -a
