sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

cache: 
  directories:
  - $HOME/.m2

env:
  - TRAVISCI=1

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - cd bin
  - ./build.sh
  - cd ..

  - docker images

  - docker-compose -p "dev" -f docker-compose.dev.yml up -d

  - cd ..
  - git clone https://github.com/jameshnsears/xqa-test-data
  - docker run -d --net="dev_xqa" --name="dev_xqa-ingest_1" -v /home/travis/build/jameshnsears/xqa-test-data:/xml xqa-ingest:latest -message_broker_host xqa-message-broker -path /xml

  - sleep 60
  - docker ps -a
  - sleep 60

  - docker logs dev_xqa-shard_1 | grep "size=40" xqa-shard_1.log
