sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - docker-compose -p "prod" -f docker-compose.prod.yml up -d

  - cd ..
  - git clone https://github.com/jameshnsears/xqa-test-data

  - docker run -d --net="prod_xqa" --name="prod_xqa-ingest_1" -v /home/travis/build/jameshnsears/xqa-test-data:/xml jameshnsears/xqa-ingest:latest -message_broker_host xqa-message-broker -path /xml
  - sleep 180

  - docker logs prod_xqa-shard_1 > xqa-shard_1.log
  - grep "size=40" xqa-shard_1.log
