sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

  - docker-compose -p "dev" -f docker-compose.prod.yml -f docker-compose.prod.shard.yml up -d

script:
  - cd ..
  - git clone https://github.com/jameshnsears/xqa-test-data
  - chmod 777 xqa-test-data/*.xml
  - rm -rf xqa-test-data/.git 

  - docker run -d --net="dev_xqa" --name="dev_xqa-ingest_1" -v /home/travis/build/jameshnsears/xqa-test-data:/xml jameshnsears/xqa-ingest:latest -message_broker_host xqa-message-broker -path /xml
  - sleep 180

  - docker logs dev_xqa-ingest_1

  - docker logs dev_xqa-ingest-balancer_1

  - docker logs dev_xqa-shard_1 > xqa-shard_1.log
  - cat xqa-shard_1.log

  - grep "size=40" xqa-shard_1.log
