version: '3'

services:
  xqa-db:
    image: xqa-db:latest
    volumes:
      - "xqa-db:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - xqa

  xqa-db-amqp:
    image: xqa-db-amqp:latest
    command: ["-message_broker_host", "xqa-message-broker", "-storage_host", "xqa-db"]
    networks:
      - xqa
    depends_on:
      - xqa-db
      - xqa-message-broker

  xqa-ingest-balancer:
    image: xqa-ingest-balancer:latest
    command: ["-message_broker_host", "xqa-message-broker"]
    environment:
      - POOL_SIZE
    networks:
      - xqa
    depends_on:
      - xqa-message-broker

  xqa-message-broker:
    image: xqa-message-broker:latest
    ports:
      - "5672:5672"
      - "8161:8161"
    volumes:
      - "xqa-message-broker:/opt/apache-activemq-5.15.3/data"
    networks:
      - xqa

  xqa-shard:
    image: xqa-shard:latest
    command: ["-message_broker_host", "xqa-message-broker"]
    networks:
      - xqa
    depends_on:
      - xqa-message-broker

volumes:
  xqa-db:
  xqa-message-broker:

networks:
  xqa:
